// ======================================================
// NOVA DIGITAL - PRODUCT DATA (shared by shop.js and home.js)
// ======================================================

const products = {
  laptops: [
    {
      name: "ASUS TUF F15",
      spec: "Core i7 • RTX4060",
      price: "72,900,000",
      image: "",
      badge: "15%",
      brand: "ASUS",
    },
    {
      name: "Lenovo Legion 5",
      spec: "Ryzen 7 • RTX4060",
      price: "69,500,000",
      image: "shopeimage/laptop/image-laptop-2.png",
      badge: "12%",
      brand: "Lenovo",
    },
    {
      name: "MSI Katana",
      spec: "Core i7 • RTX4050",
      price: "67,800,000",
      image: "shopeimage/laptop/image-laptop-3.png",
      badge: "10%",
      brand: "MSI",
    },
    {
      name: "HP Victus",
      spec: "Ryzen 5 • RTX3050",
      price: "55,900,000",
      image: "shopeimage/laptop/image-laptop-4.png",
      badge: "8%",
      brand: "HP",
    },
    {
      name: "MacBook Air M3",
      spec: "Apple M3 • 16GB",
      price: "95,000,000",
      image: "shopeimage/laptop/image-laptop-5.png",
      badge: "5%",
      brand: "Apple",
    },
  ],

  mobiles: [
    {
      name: "Galaxy S25 Ultra",
      spec: "512GB",
      price: "64,900,000",
      image: "shopeimage/phone/SOPHE-PHONE1.png",
      badge: "10%",
      brand: "Samsung",
    },
    {
      name: "iPhone 16 Pro",
      spec: "256GB",
      price: "98,000,000",
      image: "shopeimage/phone/SHOPE-PHONE2.png",
      badge: "5%",
      brand: "Apple",
    },
    {
      name: "Xiaomi 15",
      spec: "512GB",
      price: "41,000,000",
      image: "shopeimage/phone/SHOPE-PHNE3.png",
      badge: "15%",
      brand: "Xiaomi",
    },
    {
      name: "Nothing Phone 3",
      spec: "256GB",
      price: "37,500,000",
      image: "shopeimage/phone/SHOPE-PHNE5.png",
      badge: "7%",
      brand: "Nothing",
    },
    {
      name: "Pixel 10 Pro",
      spec: "256GB",
      price: "58,000,000",
      image: "shopeimage/phone/SHOPE-PHNE4.png",
      badge: "11%",
      brand: "Google",
    },
    {
      name: "realme GT7",
      spec: "256GB",
      price: "58,000,000",
      image: "shopeimage/phone/SHOPE-PHNE8.png",
      badge: "11%",
      brand: "realme",
    },
    {
      name: "OnePlus 13",
      spec: "256GB",
      price: "58,000,000",
      image: "shopeimage/phone/SHOPE-PHNE6.png",
      badge: "11%",
      brand: "OnePlus",
    },
    {
      name: "POCO F6 Pro",
      spec: "256GB",
      price: "58,000,000",
      image: "shopeimage/phone/SHOPE-PHNE7.png",
      badge: "11%",
      brand: "POCO",
    },
    {
      name: "iPhone SE (2022)",
      spec: "256GB",
      price: "58,000,000",
      image: "shopeimage/phone/SHOPE-PHNE10.png",
      badge: "11%",
      brand: "Apple",
    },
    {
      name: "Galaxy A56 5G",
      spec: "256GB",
      price: "58,000,000",
      image: "shopeimage/phone/SHOPE-PHNE9.png",
      badge: "11%",
      brand: "Samsung",
    },
  ],

  monitors: [
    {
      name: "LG UltraWide",
      spec: "34 Inch",
      price: "38,000,000",
      image: "image/monitor1.png",
      badge: "12%",
      brand: "LG",
    },
    {
      name: "ASUS ProArt",
      spec: "32 Inch",
      price: "42,000,000",
      image: "image/monitor2.png",
      badge: "8%",
      brand: "ASUS",
    },
    {
      name: "Samsung Odyssey",
      spec: "27 Inch",
      price: "31,000,000",
      image: "image/monitor3.png",
      badge: "18%",
      brand: "Samsung",
    },
    {
      name: "MSI Gaming",
      spec: "165Hz",
      price: "26,000,000",
      image: "image/monitor4.png",
      badge: "10%",
      brand: "MSI",
    },
    {
      name: "BenQ Designer",
      spec: "4K",
      price: "36,000,000",
      image: "image/monitor5.png",
      badge: "9%",
      brand: "BenQ",
    },
  ],

  headphones: [
    {
      name: "Sony XM5",
      spec: "Wireless",
      price: "16,900,000",
      image: "image/headphone1.png",
      badge: "12%",
      brand: "Sony",
    },
    {
      name: "AirPods Pro 2",
      spec: "USB-C",
      price: "18,500,000",
      image: "image/headphone2.png",
      badge: "6%",
      brand: "Apple",
    },
    {
      name: "Galaxy Buds 3",
      spec: "ANC",
      price: "9,200,000",
      image: "image/headphone3.png",
      badge: "15%",
      brand: "Samsung",
    },
    {
      name: "JBL Tune",
      spec: "Bluetooth",
      price: "4,900,000",
      image: "image/headphone4.png",
      badge: "20%",
      brand: "JBL",
    },
    {
      name: "Razer BlackShark",
      spec: "Gaming",
      price: "7,500,000",
      image: "image/headphone5.png",
      badge: "10%",
      brand: "Razer",
    },
  ],

  accessories: [
    {
      name: "Mechanical Keyboard",
      spec: "RGB",
      price: "4,200,000",
      image: "image/acc1.png",
      badge: "18%",
      brand: "Generic",
    },
    {
      name: "Gaming Mouse",
      spec: "Wireless",
      price: "3,100,000",
      image: "image/acc2.png",
      badge: "10%",
      brand: "Generic",
    },
    {
      name: "USB Hub",
      spec: "Type-C",
      price: "1,400,000",
      image: "image/acc3.png",
      badge: "15%",
      brand: "Generic",
    },
    {
      name: "Laptop Stand",
      spec: "Aluminium",
      price: "1,800,000",
      image: "image/acc4.png",
      badge: "8%",
      brand: "Generic",
    },
    {
      name: "SSD 1TB",
      spec: "NVMe",
      price: "5,700,000",
      image: "image/acc5.png",
      badge: "12%",
      brand: "Generic",
    },
  ],
};
